spring.application.name=user-api
server.port=8081
spring.kafka.bootstrap.servers=localhost:9092
spring.kafka.consumer.group-id=user-api-group

kafka.topic.user-create-request=user-create-request
kafka.topic.user-update-request=user-update-request
kafka.topic.user-delete-request=user-delete-request
kafka.topic.user-get-by-id-request=user-get-by-id-request
kafka.topic.user-get-by-id-result=user-get-by-id-result
