spring.application.name=persistence-api
server.port=8082
spring.datasource.url=jdbc:postgresql://localhost:5432/user_db
spring.datasource.username=root
spring.datasource.password=1033
spring.jpa.hibernate.ddl-auto=update

spring.kafka.bootstrap-servers=localhost:9092
spring.kafka.consumer.group-id=user-persistence-group
spring.kafka.consumer.auto-offset-reset=earliest

kafka.topic.user-create-request=user-create-request
kafka.topic.user-update-request=user-update-request
kafka.topic.user-delete-request=user-delete-request
kafka.topic.user-get-by-id-request=user-get-by-id-request
kafka.topic.user-get-by-id-result=user-get-by-id-result
